apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkitd-config
  labels:
    app.kubernetes.io/name: buildkitd
    app.kubernetes.io/creator: hossein-yousefi
    app.kubernetes.io/stack: build-docker-image    
data:
  buildkit.toml: |
    root = "/var/lib/buildkit"
    [log]
      format = "text"
